[project]
name = "window-temp-alert"
version = "0.2.1"
description = "App that tells you when you can open your window in the summer evenings."
readme = "README.md"
requires-python = ">=3.8"
dependencies = ["pgeocode>=0.5.0"]

[tool.setuptools]
packages = ["window_temp"]
