[project]
name = "window-temp-alert"
version = "0.1.0"
description = "App that tells you when you can open your window in the summer evenings."
readme = "README.md"
requires-python = ">=3.8"
dependencies = ["pgeocode>=0.5.0"]
